- name: Install NGINX
  hosts: all
  tasks:        
    - name: Install nginx
      yum:
        name: nginx
        state: present
      
    - name: Insert Index Page
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        
    - name: Start NGiNX
      service:
        name: nginx
      state: started   
      
    - name: Nginx Message
      debug:
        msg: "Nginx installé !"
